const SCOPE = {
  limited: [
    { method: 'get', url: '/movie/genres' },
    { method: 'delete', url: '/movie/:movie/' },
    { method: 'get', url: '/movie/:movie/' },
    { method: 'post', url: '/movie/:movie/report' },
    { method: 'delete', url: '/movie' },
    { method: 'get', url: '/movie' },
    { method: 'get', url: '/oauth/' },
    { method: 'get', url: '/token/:token' },
    { method: 'get', url: '/token/:token/verify' },
    { method: 'get', url: '/token/blacklist' },
    { method: 'get', url: '/torrent/:torrent/status' },
    { method: 'post', url: '/torrent/:torrent/report' },
    { method: 'get', url: '/torrent/all/active' },
    { method: 'get', url: '/torrent/all/status' },
    { method: 'get', url: '/torrent/encoded-upload' },
    { method: 'get', url: '/torrent/upload' },
    { method: 'get', url: '/user/:id' },
    { method: 'get', url: '/user/login' },
  ],
  full: [
    { method: 'get', url: '/movie/genres' },
    { method: 'delete', url: '/movie/:movie/' },
    { method: 'get', url: '/movie/:movie/' },
    { method: 'post', url: '/movie/:movie/comment' },
    { method: 'delete', url: '/movie' },
    { method: 'get', url: '/movie' },
    { method: 'get', url: '/oauth/' },
    { method: 'post', url: '/oauth/' },
    { method: 'get', url: '/token/:token' },
    { method: 'get', url: '/token/:token/verify' },
    { method: 'post', url: '/token/blacklist' },
    { method: 'get', url: '/torrent/:torrent/status' },
    { method: 'post', url: '/torrent/:torrent/report' },
    { method: 'get', url: '/torrent/all/active' },
    { method: 'get', url: '/torrent/all/status' },
    { method: 'get', url: '/torrent/encoded-upload' },
    { method: 'get', url: '/torrent/files' },
    { method: 'get', url: '/torrent/status' },
    { method: 'get', url: '/torrent/upload' },
    { method: 'put', url: '/user/confirm-account' },
    { method: 'put', url: '/user/forgotten-password' },
    { method: 'put', url: '/user/recover-password' },
    { method: 'put', url: '/user/password/:id' },
    { method: 'put', url: '/user/picture/:id' },
    { method: 'get', url: '/user/all' },
    { method: 'get', url: '/oauth/login' },
    { method: 'get', url: '/user/login' },
    { method: 'get', url: '/user/:id' },
    { method: 'delete', url: '/user/:id' },
    { method: 'post', url: '/user' },
    { method: 'put', url: '/user/:id' },
  ],
}

module.exports = SCOPE
