const SCOPE = {
  limited: [
    { method: 'get', url: '/movie/genres' },
    { method: 'delete', url: '/movie/:movie/' },
    { method: 'get', url: '/movie/:movie/' },
    { method: 'post', url: '/movie/:movie/report' },
    { method: 'delete', url: '/movie' },
    { method: 'get', url: '/movie' },
    { method: 'get', url: '/token/:token' },
    { method: 'get', url: '/token/:token/verify' },
    { method: 'get', url: '/token/blacklist' },
    { method: 'get', url: '/torrent/:torrent/status' },
    { method: 'post', url: '/torrent/:torrent/report' },
    { method: 'get', url: '/torrent/all/active' },
    { method: 'get', url: '/torrent/all/status' },
    { method: 'get', url: '/torrent/encoded-upload' },
    { method: 'get', url: '/torrent/upload' },
  ],
  full: [
    { method: 'get', url: '/movie/genres' },
    { method: 'delete', url: '/movie/:movie/' },
    { method: 'get', url: '/movie/:movie/' },
    { method: 'post', url: '/movie/:movie/comment' },
    { method: 'delete', url: '/movie' },
    { method: 'get', url: '/movie' },
    { method: 'get', url: '/token/:token' },
    { method: 'get', url: '/token/:token/verify' },
    { method: 'post', url: '/token/blacklist' },
    { method: 'get', url: '/torrent/:torrent/status' },
    { method: 'post', url: '/torrent/:torrent/report' },
    { method: 'get', url: '/torrent/all/active' },
    { method: 'get', url: '/torrent/all/status' },
    { method: 'get', url: '/torrent/encoded-upload' },
    { method: 'get', url: '/torrent/files' },
    { method: 'get', url: '/torrent/status' },
    { method: 'get', url: '/torrent/upload' },
  ],
}

module.exports = SCOPE
